
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CustomerEntities.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Tenant
{

    public int Id { get; set; }

    public string TenantName { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string City { get; set; }

    public string Zipcode { get; set; }

    public string Country { get; set; }

    public string LogoPath { get; set; }

    public Nullable<int> BuildingId { get; set; }

    public Nullable<double> AreaField { get; set; }

    public Nullable<bool> AfterHourApplicable { get; set; }

    public Nullable<double> Rate { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<int> TenantTypeId { get; set; }

    public Nullable<int> NoOfMeters { get; set; }

    public Nullable<double> LettedArea { get; set; }

    public string IsAHU { get; set; }

    public string Type { get; set; }

    public string LeaseId { get; set; }

    public string EmailAddress { get; set; }

}

}
