
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CustomerEntities.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class UserM
{

    public int UserID { get; set; }

    public Nullable<int> UserTypeID { get; set; }

    public Nullable<int> LevelID { get; set; }

    public string UserName { get; set; }

    public string DisplayName { get; set; }

    public string UserPassword { get; set; }

    public Nullable<int> PasswordExpDays { get; set; }

    public Nullable<int> PasswordAttempt { get; set; }

    public Nullable<int> PasswordLockout { get; set; }

    public Nullable<bool> GSM { get; set; }

    public Nullable<bool> BulkSMS { get; set; }

    public Nullable<bool> Email { get; set; }

    public Nullable<System.DateTime> ExpiryDate { get; set; }

    public Nullable<long> APIID { get; set; }

    public Nullable<bool> BlkUser { get; set; }

    public string Status { get; set; }

    public Nullable<int> TenantId { get; set; }

}

}
